# Generated by Django 3.1.2 on 2020-11-02 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RESTRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(blank=True, default=None, help_text='When the request will start', null=True)),
                ('completed', models.DateTimeField(blank=True, default=None, help_text='When the request is completed', null=True)),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PATCH', 'Patch'), ('DELETE', 'Delete')], default='GET', max_length=6)),
                ('url', models.URLField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='The user who created the request', on_delete=django.db.models.deletion.CASCADE, related_name='rest_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RESTResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('headers', models.JSONField(null=True)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('data', models.JSONField(null=True)),
                ('rest_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rest_response', to='rest_request.restrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
